//! DocSync trait — replacement for the Synced trait.

use loro::LoroDoc;

use crate::error::{HydrateError, ReconcileError};
use crate::hydrate::Hydrate;
use crate::reconcile::{Reconcile, RootReconciler};

/// Types that can be serialized to/from a Loro document at a named root key.
///
/// Generated by `#[derive(Hydrate, Reconcile)]` with `#[loro(root = "key")]`.
/// Replaces the manual `Synced` trait.
pub trait DocSync: Hydrate + Reconcile {
    /// The root map key in the LoroDoc.
    const ROOT_KEY: &'static str;

    /// Reconstruct from a Loro document.
    fn from_doc(doc: &LoroDoc) -> Result<Self, HydrateError> {
        let map = doc.get_map(Self::ROOT_KEY);
        Self::hydrate_map(&map)
    }

    /// Write into a Loro document.
    fn to_doc(&self, doc: &LoroDoc) -> Result<(), ReconcileError> {
        let map = doc.get_map(Self::ROOT_KEY);
        let reconciler = RootReconciler::new(map);
        self.reconcile(reconciler)
    }
}
